name: ice
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - gdal=3.5.1
  - matplotlib=3.5.2
  - numpy=1.23.1
  - pandas=1.4.3
  - pip=22.1.2
  - python=3.10.5
  - pytorch=1.12.0
  - rasterio=1.3.2
  - rioxarray=0.11.1
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - seaborn=0.11.2
  - tensorboardx=2.5.1
  - torchvision=0.13.0
  - tqdm=4.64.0
  - xarray=0.20.1
  - pip:
      - kornia==0.6.5
      - pytorch-lightning==1.6.4
      - tensorboard==2.11.0
      - torchmetrics==0.10.3
